### PR TITLE
Painting the bikeshed (tiny CSS tweaks)

### PR DESCRIPTION
**Pull request by samlh**
Some minor CSS tweaks, feel free to ignore

### CODE REVIEW

**Comment by fieu** [comment]
This is a good one. I suggest merging it @diafygi.

**Comment by diafygi** [comment]
Yep, at work. Will try to review tonight :)

**Comment by fieu** [comment]
I've tried them with 'Inspect Element' in my browser and they look good. I like what you did with the `.help-content`. Nice border. Simple but nice.

**Comment by diafygi** [comment]
Looks good, thanks!

**Pull request merged**
