### PR TITLE
typo

### PR DESCRIPTION
**Pull request by ineeee**
Sorry. It was annoying me.

### CODE REVIEW

**Comment by ThomasLomas** [comment]
Me too: https://github.com/diafygi/gethttpsforfree/pull/65

**Comment by rugk** [comment]
When will this be merged?

**Comment by ineeee** [comment]
I believe the repo is abandoned. The last commit was almost two months ago.

**Comment by diafygi** [comment]
@inexist3nce it's not abandoned, I'm just currently swamped at work. Will review pull requests later this spring or summer. Patience!

**Pull request merged**
